fixed: patch error

diff --git a/HelperResources/CommonResources b/HelperResources/CommonResources
--- a/HelperResources/CommonResources
+++ b/HelperResources/CommonResources
@@ -686,7 +686,7 @@ restoreActiveFile ()
 		#	if success, don't restore original
 		previousPatchFile="$previousPatchesDir/$baseName.patch"
 		if [ -e "$previousPatchFile" ] && 
-			yes 'no' | patch -R "$activeFile" "$previousPatchFile" > /dev/null ; then
+			yes 'no' | patch -R "$activeFile" "$previousPatchFile" &> /dev/null ; then
 				restoreOriginal=false
 		# no previous patch file or reverse patch failed
 		#	original will be restored
@@ -1581,60 +1581,86 @@ if ! [ -z "$fileListPatched" ];then
 	for file in ${fileListPatched[@]}; do
 		baseName=$( basename $file )
 		tempActiveFile="$tempFileDir/$baseName"
+
 		if [ -e "$file" ] ; then
 			previousPatchFile="$previousPatchesDir/$baseName.patch"
-			cp "$file" "$tempActiveFile"
 
-			# remove a previous patch for this package
-			# if this succeeds proceed with forward patch on temp file
-			useTempActiveFile=false
-			if [ -e "$previousPatchFile" ] && [ -e "$file.package" ] \
-						&& (( $( grep -c $packageName "$file.package" ) > 0 )); then
-				if yes 'no' | patch -R "$tempActiveFile" "$previousPatchFile" &> /dev/null ; then
-					useTempActiveFile=false
-				else
-					rm "$previousPatchFile"
-				fi
+			# chek for this package and others in .package list
+			packageList="$file.package"
+			thisPackageInList=false
+			otherPackagesInList=false
+			if [ -f "$packageList" ]; then
+				previousPackages=$( cat "$packageList" )
+				for previousPackage in ${previousPackages[@]}; do
+					if [ $packageName == $previousPackage ]; then
+						thisPackageInList=true
+					else
+						otherPackagesInList=true
+					fi
+				done
 			fi
 
-			# attempt to patch the active file with any file ending in .patch
-			# the first one that successfully creates a forward AND reverse patch is used
-			forwardPatched="$tempFileDir/$baseName".patchedForInstall
-
+			cp "$file" "$tempActiveFile"
 			patchOk=false
-			reversePatchTest="$tempFileDir/$baseName.reversePatchTest"
-
-			patchFiles=( $( ls "$patchSourceDir/$baseName"*.patch ) )
-			for patchFile in ${patchFiles[@]};do
-				# if this package is still installed and it's modificaitons
-				#	could be removed from the active file, then patch that
-				if $useTempActiveFile ; then
-					cp "$tempActiveFile" "$forwardPatched"
-				# otherwise start with the active file itself
+			# package not currently in .package list - patch active file
+			if ! $thisPackageInList; then
+				patchOk=true
+			# attempt to remove the previous patch for this package
+			# if this succeeds proceed with forward patch on result
+			elif [ -e "$previousPatchFile" ]; then
+				if yes 'no' | patch -R "$tempActiveFile" "$previousPatchFile" &> /dev/null ; then
+					patchOk=true
+				# reverse patch failed
 				else
-					cp "$file" "$forwardPatched"
+					patchErrors+=( "unable to remove previous patch for $baseName" )
+					rm "$previousPatchFile"
 				fi
-				if yes 'no' | patch -N "$forwardPatched" "$patchFile" > /dev/null ; then
-					# forward patch succeeded - test reverse patch (both must succeed)
-					cp "$forwardPatched" "$reversePatchTest"
-					if yes 'no' | patch -R "$reversePatchTest" "$patchFile" > /dev/null ; then
-						patchOk=true
-					fi
-				fi
-			done
-			currentPatchFile="$tempFileDir/$baseName.currentPatch"
-			if $patchOk ; then
-				# save this so patch file used for install can be saved for evenutal uninstall
-				#	or to reverse patch prior to reinstall
-				cp "$patchFile" "$currentPatchFile"
+			# no previous patch file
+			# active file prpbably modified by direct replaceent by this package
+			# patch .orig in stead of active file
+			elif ! $otherPackagesInList && [ -e "$file.orig" ]; then
+				cp "$file.orig" "$tempActiveFile"
+				patchOk=true
+			elif ! [ -e "$file.orig" ]; then
+				patchErrors+=( "$baseName no original for patch" )
 			else
-				patchErrors+=( "patch unsuccesful for $baseName" )
-				rm -r "$forwardPatched"
-				rm -f "$currentPatchFile"
+				patchErrors+=( "$baseName modified by other packages - and no previous patch for $packageName" )
+			fi
+
+			# a suitable source for the patch was located above
+			if $patchOk; then
+				# attempt to patch the active file with any file ending in .patch
+				# the first one that successfully creates a forward AND reverse patch
+				# .patchedForInstall provides the patched file for updateActiveFile
+				forwardPatched="$tempFileDir/$baseName".patchedForInstall
+				reversePatchTest="$tempFileDir/$baseName.reversePatchTest"
+				patchFiles=( $( ls "$patchSourceDir/$baseName"*.patch ) )
+				patchFound=false
+				for patchFile in ${patchFiles[@]};do
+					cp "$tempActiveFile" "$forwardPatched"
+					if yes 'no' | patch -N "$forwardPatched" "$patchFile" &> /dev/null ; then
+						# forward patch succeeded - test reverse patch (both must succeed)
+						cp "$forwardPatched" "$reversePatchTest"
+						if yes 'no' | patch -R "$reversePatchTest" "$patchFile" &> /dev/null ; then
+							patchFound=true
+							break
+						fi
+					fi
+				done
+				currentPatchFile="$tempFileDir/$baseName.currentPatch"
+				if $patchFound ; then
+					# save this so patch file used for install can be saved for evenutal uninstall
+					#	or to reverse patch prior to reinstall
+					cp "$patchFile" "$currentPatchFile"
+				else
+					patchErrors+=( "patch unsuccesful for $baseName" )
+					rm -r "$forwardPatched"
+					rm -f "$currentPatchFile"
+				fi
 			fi
 			rm -f "$reversePatched" "$reversePatchTest"
 		else
-			patchErrors+=( "no original for $baseName patch" )
+			patchErrors+=( "$baseName no active file for patch" )
 			continue
 		fi
 	done # for file
