resize root partition and check for room on file systems before allowing install

diff --git a/CommonResources b/CommonResources
--- a/CommonResources
+++ b/CommonResources
@@ -174,17 +174,18 @@ backupActiveFile ()
 #
 # updateActiveFile sourceFile activeFile
 #   a separate source (replacement) file is specified
-#     either as a full path to the actual file
-#     or as the basename of a file to be found in the version directory or FileSets
+#
+# both sourceFile and activeFile must be a full path to the file
 #
 # if the update fails, scriptAction is changed to UNINSTALL
 
 updateActiveFile ()
 {
-    sourceFound=false
     thisFileUpdated=false
-    
-    sourceFile="$1"
+    local sourceFound=false
+	local baseName
+    local sourceFile="$1"
+    local destinationFile
 
     # separate replacement file specified
     if [ $# == 2 ]; then
@@ -199,13 +200,13 @@ updateActiveFile ()
     
     # look for source in FileSets
     if ! $sourceFound ; then
-        sourceFile="$(basename "$sourceFile")"
+		baseName="$(basename "$sourceFile")"
         # found in version directory
-        if [ -f "$fileSet/$sourceFile" ]; then
-            sourceFile="$fileSet/$sourceFile"
+        if [ -f "$fileSet/$baseName" ]; then
+            sourceFile="$fileSet/$baseName"
             sourceFound=true
-        elif [ -f "$pkgFileSets/$sourceFile" ]; then
-            sourceFile="$pkgFileSets/$sourceFile"
+        elif [ -f "$pkgFileSets/$baseName" ]; then
+            sourceFile="$pkgFileSets/$baseName"
             sourceFound=true
         fi
     fi
@@ -217,10 +218,8 @@ updateActiveFile ()
             return
         # if not flagged, this is a fatal error
         else
-            logMessage "ERROR: no replacement file for $sourceFile"
-            thisFileUpdated=false
+            logMessage "ERROR: no soure file for replacement - can't continue with install'"
             scriptAction='UNINSTALL'
-			touch "$fileSet/INCOMPLETE"
             installFailed=true
         fi
         return
@@ -640,9 +639,17 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-# make sure rootfs is mounted R/W
-if [ -f /opt/victronenergy/swupdate-scripts/remount-rw.sh ]; then
-    /opt/victronenergy/swupdate-scripts/remount-rw.sh
+# make sure rootfs is mounted R/W & and resized to allow space for replacement files
+if [ -f /opt/victronenergy/swupdate-scripts/resize2fs.sh ]; then
+    /opt/victronenergy/swupdate-scripts/resize2fs.sh
+fi
+
+# make sure the root partition has space for the package
+#	arbitrary minimum size of 10 MB for now
+availableSpace=$(df -m / | tail -1 | awk '{print $4}')
+if (( $availableSpace < 10 )); then
+	logMessage "no room for modified files on /root ($availableSpace MB remaining) - can't continue"
+	exit $EXIT_ROOT_FULL
 fi
 
 # move old installedFlag ("...inInstalled...")
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -57,12 +57,22 @@ fi
 
 if [ $scriptAction == 'INSTALL' ] ; then
 	# modify PageSettings here so SetupHelper is independent of Venus OS verison
+	origFile=""
 	if [ -f "$qmlDir/PageSettings.qml.orig" ]; then
-		origFile="$qmlDir/PageSettings.qml.orig"
-	else
-		origFile="$qmlDir/PageSettings.qml"
+		lineCount=$(wc "$qmlDir/PageSettings.qml.orig" | awk '{print $1}')
+		if (( $lineCount > 50 )); then
+			origFile="$qmlDir/PageSettings.qml.orig"
+		fi
+	elif [ -z "$origFile" ]; then
+		lineCount=$(wc "$qmlDir/PageSettings.qml" | awk '{print $1}')
+		if (( $lineCount > 50 )); then
+			origFile="$qmlDir/PageSettings.qml"
+		fi
 	fi
-	if (( $(grep -c "PackageManager" $origFile) > 0)); then
+	if [ -z "$origFile" ]; then
+		logMessage "ERROR: PageSettings.qml not found - can't continue"
+		exit $EXIT_ERROR
+	elif (( $(grep -c "PackageManager" $origFile) > 0)); then
 		logMessage "WARNING: PageSettings.qml already modified for PackageManager -- skipping that modification"
 	else
 		rm -f "/var/volatile/tmp/PageSettings.qml"
@@ -70,6 +80,10 @@ if [ $scriptAction == 'INSTALL' ] ; then
 		# find line with second to last }
 		insertBefore=$(awk '{print NR  " " $s}' "$origFile" | grep '}' | tail -2 | head -n 1 | awk '{print $1}')
 		((insertBefore -= 1))
+		if (( $insertBefore < 10 )); then
+			logMessage "ERROR: PageSettings.qml could not be modified - can't continue"
+			exit $EXIT_ERROR
+		fi
 		# include all lines before that one
 		head -n $insertBefore $origFile >> "/var/volatile/tmp/PageSettings.qml"
 		# file with PackageManager menu code includes the last two }
