fixed: install button in package edit menu sometimes drawn in wrong posisition

diff --git a/updateFileSets b/updateFileSets
--- a/updateFileSets
+++ b/updateFileSets
@@ -1,38 +1,50 @@
 #!/bin/bash
 
 # this script updates file sets for all packages in the list below
-# it scans all Venus OS versions in the originalFiles directory
+# it scans all Venus OS versions in the stockFiles directory
 #
 # This is a unix bash script and should be run on a host computer, not a GX device
 # Windows will not run this script natively.
 # However Windows 10 apparently supports bash:
 # https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/
 #
-# packages to be evaulated may be specified on the command line when calling this script
-# without options, packages in the allPackages list will be evaluated
+# packages to be evaulated may be specified on the command line
+# use 'all' to process all packages in the allPackages list below
 #
-# originalFiles contains "master" file sets for all Venus files
+# only file sets for released versions will be created/updated
+# the highest numbered beta version will be included if there is no newer released version
+# if v2.2~4, v2.2~5 and v2.2 all exist, no file sets will be created for ~4 and ~5 
+# if v2.2~4, v2.2~5 exist, no file sets will be created for ~4
+#
+# include betas on the command line if file sets for all beta versions should be created/updated
+#
+# stockFiles contains "master" file sets for all Venus files
 # excerpts from Venus OS file systems must be stored on the host
 # within a directory with name of the exact Venus OS version
-# and withn the originalFiles directory defined below.
+# and within the stockFiles directory defined below.
 #
 # 1) missing file set directories are created
 # 2) if any files in fileList don't exist (eg, a new file was added to file list),
 #   the original file in /opt and /etc is copied to the version directory
-# 3) if the original file does not exist, the file set is so marked with .NO_ORIG
+# 3) if the original file does not exist, the file is so marked with .NO_ORIG
 # 4) version-dependent files without an original can use an "alternate original"
 #   specified in FileSets. This permits version checks for these files too
 # 5) file sets that contain no files are removed, minimizing the number of file sets
 #   to check for a matching original
 #
+# when a stock file set does not exist, this script will check files from existing file sets
+#	to create other versions
+#
+# existing file sets not in the releasedVersionList should be empty after the script runs
+#	and will be deleted automatically
 
 # set allPackages to all packages this script should evalueate if no options are included
 allPackages="SetupHelper GuiMods ExtTransferSwitch ShutdownMonitor VeCanSetup RpiDisplaySetup RpiGpioSetup"
-### GeneratorConnector TankRepeater are currently obsolete and file sets should not be updated.
+## GeneratorConnector TankRepeater are obsolete and file sets should not be updated.
 
 # set these as appropriate to your system
 packageRoot="/Users/Kevin/Documents/GitHub"
-originalFiles="$packageRoot/OriginalVenusOsFiles"
+stockFiles="$packageRoot/StockVenusOsFiles"
 
 ((totalErrors=0))
 ((totalWarnings=0))
@@ -74,34 +86,57 @@ function versionStringToNumber ()
 	fi
 }
 
+#### script code begins here
 
-if [ -z $1 ]; then
+includeBetas=false
+
+packageList=""
+doAllPackages=false
+for param in $* ; do
+	if [ "$param" == "betas" ]; then
+		includeBetas=true
+	elif [ "$param" == "all" ]; then
+		doAllPackages=true
+	else
+		packageList+=" "$1
+	fi
+	shift
+done
+if $doAllPackages ; then
     packageList=$allPackages
-else
-    packageList=$*
+elif [ -z "$packageList" ]; then
+	logMessage "ERROR no packages specified - use 'all' for all packages"
+	exit
 fi
 
-# check to make sure the dictory name matches /opt/victronenergy/version
-rm -f /tmp/foo
-rawVersionList=($(ls -d "$originalFiles"/v*))
-for ver in ${rawVersionList[@]} ; do
-    version=$(basename $ver)
-    versionFile="$originalFiles/$version/opt/victronenergy/version"
+# make the version list from the directories in stock files
+# version lists are sorted so the most recent version is first
+# if includeBetas is false, remove all betas except the highest version
+tempList=""
+versionList=($(ls -d "$stockFiles"/v* 2> /dev/null))
+for entry in ${versionList[@]} ; do
+    version=$(basename $entry)
+    versionFile="$stockFiles/$version/opt/victronenergy/version"
     realVersion=$(cat "$versionFile" | head -n 1)
 
     if [ $version != $realVersion ]; then
-        directoryName=$(basename $originalFiles)/$version
+        directoryName=$(basename $stockFiles)/$version
         logMessage "ERROR $directoryName name does not mactch Venus $realVersion - can't continue"
-		rm -f /tmp/foo
         exit
     fi
 	versionStringToNumber $version
-	echo "$version $versionNumber" >> /tmp/foo
+	tempList+=("$version:$versionNumber")
 done
-
-# versionList is sorted in reverse version order
-versionList=( $(sort -r -n -k 2 /tmp/foo | awk '{print $1}') )
-rm -f /tmp/foo
+versionList=( $(echo ${tempList[@]} | tr ' ' '\n' | sort -t ':' -r -n -k 2 | uniq ) )
+firstEntry=true
+fileSetList=""
+for entry in ${versionList[@]} ; do
+	version=$(echo $entry | awk -F ':' '{print $1}')
+	if $firstEntry || $includeBetas || [[ $version != *~* ]]; then
+		fileSetList+=($entry)
+	fi
+	firstEntry=false
+done
 
 for package in $packageList; do
     if [ ! -d "$packageRoot/$package" ] || [ ! -f "$packageRoot/$package/version" ]; then
@@ -124,8 +159,31 @@ for package in $packageList; do
     fi
 	logMessage "$package: checking file sets"
 
-    for index1 in ${!versionList[@]} ; do
-		version1=${versionList[$index1]}
+	# add a package's existing file sets to fileSetList
+	# all directories in allVersions will be scanned looking for content to populate each file set
+	existingFileSets=($(ls -d "$packageFiles"/v* 2> /dev/null))
+	tempList=(${fileSetList[@]})
+	for entry in ${existingFileSets[@]} ; do
+		version=$(basename $entry)
+		versionStringToNumber $version
+			tempList+=($version:$versionNumber)
+	done
+	allVersions=( $(echo ${tempList[@]} | tr ' ' '\n' | sort -t ':' -r -n -k 2 | uniq ) )
+	
+	# clean up flag files from a previous run
+	for fileSet in ${existingFileSets[@]} ; do
+		rm -f "$fileSet/INCOMPATIBLE_VERSION"
+		rm -f "$fileSet/RETAIN_THIS_VERSION"
+		rm -f "$fileSet/UNUSED_FILE_SET"
+		rm -f "$fileSet/NEW_FILE_SET"
+		rm -f "$fileSet/"*.NO_ORIG
+		rm -f "$fileSet/"*.NO_REPLACEMENT
+		rm -f "$fileSet/"*.CHECK_REPLACEMENT
+	done
+
+    for entry1 in ${fileSetList[@]} ; do
+		IFS=':' read version1 version1number <<< "$entry1"
+		fileSetInUse=false
         fileSet1="$packageFiles/$version1"
 
         # check to see if package is compatible with this Venus version
@@ -142,25 +200,17 @@ for package in $packageList; do
 			firstVersion=0
 		fi
         
-		versionStringToNumber $version1
-		version1number=$versionNumber
-		if (( $version1number < $obsoleteVersion )) && (( $version1number >= $firstVersion )); then
+		if (( $version1number >= $obsoleteVersion )) || (( $version1number < $firstVersion )); then
 			if [ -d "$fileSet1" ]; then 
-				rm -f "$fileSet1/INCOMPATIBLE_VERSION"
-			fi
-		else
-			if [ -d "$fileSet1" ]; then 
-				logMessage "WARNING $package not compatible with Venus $version1 - file set should be removed"
+				logMessage "WARNING $package: not compatible with Venus $version1 - file set should be removed"
 				touch "$fileSet1/INCOMPATIBLE_VERSION"
 			fi
 			continue
 		fi
 
-        if [ -d "$fileSet1" ]; then
-            newFileSet=false
-        else
+        if [ ! -d "$fileSet1" ]; then
             mkdir "$fileSet1"
-            newFileSet=true
+            touch "$fileSet1/NEW_FILE_SET"
         fi
 
         for file in $fileList ; do
@@ -168,17 +218,12 @@ for package in $packageList; do
 			replacementFile1="$fileSet1/$baseName"
 			origFile1="$fileSet1/$baseName.orig"
 
-			# skip if this version matches file in prevous file set
+			# skip if this file matched one in a prevous scan
 			if [ -f "$origFile1.MATCHES_PREVIOUS" ]; then
 				continue
 			fi
 
-			# cleanup flags from previous run
-			rm -f "$fileSet1/$baseName.NO_ORIG"
-			rm -f "$fileSet1/$baseName.NO_REPLACEMENT"
-			rm -f "$fileSet1/$baseName.CHECK_REPLACEMENT"
-			
-            # alternate original if present
+            # use alternate original if present
             if [ -f "$packageFiles/$baseName.ALT_ORIG" ]; then
                 useAltOrig=true
                 altOrigFile=$(cat "$packageFiles/$baseName.ALT_ORIG")
@@ -188,80 +233,80 @@ for package in $packageList; do
             fi
             # select appropirate original file
             if $useAltOrig ; then
-				stockFile1="$originalFiles/$version1$altOrigFile"
+				stockFile1="$stockFiles/$version1$altOrigFile"
 			else
-				stockFile1="$originalFiles/$version1$file"
+				stockFile1="$stockFiles/$version1$file"
             fi
             # no original file - flag that then check for an existing replacemement
             if [ ! -f "$stockFile1" ]; then
-                logMessage "WARNING $package $version1 $baseName - no original file"
+                logMessage "ERROR $package: $version1 $baseName - no original file"
                 # flag the fact that no stock file exists
                 touch "$fileSet1/$baseName.NO_ORIG"
+                fileSetInUse=true
                 rm -f "$origFile1"
                 if [ -e $fileSet1/$baseName ]; then
                     rm -f "$fileSet1/$baseName.USE_ORIGINAL"
                 else
-                    logMessage "ERROR $package $version1 $baseName - no original so no replacement file"
+                    logMessage "ERROR $package: $version1 $baseName - no original so no replacement file"
                     touch "$fileSet1/$baseName.NO_REPLACEMENT"
                 fi
                 continue
             fi
             
-            # look for a match in another version
-			for version2 in ${versionList[@]:(($index1 + 1))} ; do
+            # look for a match in another version - use all versions, not just the release list
+			for entry2 in ${allVersions[@]} ; do
+				IFS=':' read version2 version2number <<< "$entry2"
+				if (( "$version2number" >= "$version1number" )); then
+					continue
+				fi
                 fileSet2="$packageFiles/$version2"
+
                 replacementFile2="$fileSet2/$baseName"
 				origFile2="$fileSet2/$baseName.orig"
 
 				if [ -L "$replacementFile2" ] ; then
-					logMessage "WARNING removing symlink $baseName $version2 - no longer used"
+					logMessage "$package: removing symlink $baseName $version2 - no longer used"
 					rm "$replacementFile2"
 				fi
 				if [ -L "$origFile2" ] ; then
-					logMessage "WARNING removing symlink $baseName.orig $version2 - no longer used"
+					logMessage "$package: removing symlink $baseName.orig $version2 - no longer used"
 					rm "$origFile2"
 				fi
 
-               # select appropriate original file
-				if $useAltOrig ; then
-					stockFile2="$originalFiles/$version2$altOrigFile"
-				else
-					stockFile2="$originalFiles/$version2$file"
-				fi
-                if [ ! -e "$stockFile2" ]; then
-					logMessage "ERROR $baseName $version2 stock file missing - can't continue"
-					exit
-				fi
-                
-				cmp -s "$stockFile2" "$stockFile1" > /dev/null
-				if [ $? -eq 0 ]; then
-					if [ ! -d "$fileSet2" ]; then
-						mkdir "$fileSet2"
+				# stock files exist
+				if [ -d "$stockFiles/$version2" ]; then
+				   # select appropriate original file
+					if $useAltOrig ; then
+						stockFile2="$stockFiles/$version2$altOrigFile"
+					else
+						stockFile2="$stockFiles/$version2$file"
 					fi
-					touch "$origFile2.MATCHES_PREVIOUS"
-					stockMatch=true
-				else
-					stockMatch=false
-				fi
-                
-				if $stockMatch ; then
-					# move lower versioned matching files to higher numbered version
-					if [ -f "$origFile2" ]; then
-						logMessage "moving $baseName $version2 to $version1"
-						rm -f "$origFile1"
-						mv "$origFile2" "$origFile1"
-						if [ -f "$replacementFile2" ]; then
-							rm -f "$replacementFile1"
-							mv "$replacementFile2" "$replacementFile1"
-						fi
-						if [ -f "$fileSet2/$baseName.USE_ORIGINAL" ]; then
-							rm -f "$fileSet2/$baseName.USE_ORIGINAL"
-							touch "$fileSet1/$baseName.USE_ORIGINAL"
-						fi
+					if [ ! -e "$stockFile2" ]; then
+						logMessage "ERROR $package: $baseName $version2 stock file missing - can't continue"
+						exit
 					fi
+					cmp -s "$stockFile2" "$stockFile1" > /dev/null
+					# stock files match - relocate files from fs 2 to fs 1
+					if [ $? -eq 0 ]; then
+						if [ ! -d "$fileSet2" ]; then
+							mkdir "$fileSet2"
+							touch "$fileSet2/NEW_FILE_SET"
+						fi
+						touch "$origFile2.MATCHES_PREVIOUS"
+						if [ -f "$origFile2" ]; then
+							logMessage "$package: moving $baseName $version2 to $version1 (stock)"
+							mv -f "$origFile2" "$origFile1"
+							fileSetInUse=true
+							if [ -f "$replacementFile2" ]; then
+								mv -f "$replacementFile2" "$replacementFile1"
+							fi
+							if [ -f "$replacementFile2.USE_ORIGINAL" ]; then
+								mv -f "$replacementFile2.USE_ORIGINAL" "$replacementFile1.USE_ORIGINAL"
+							fi
+							fileSetInUse=true
+						fi
 
-					if [ -f "$replacementFile1" ]; then
-						if [ -f "$replacementFile2" ]; then
+						if [ -f "$replacementFile1" ] && [ -f "$replacementFile2" ]; then
 							cmp -s "$replacementFile1" "$replacementFile2"
 							# clean up file set 2 - file set for version 1 has necessary files
 							if [ $? -eq 0 ]; then
@@ -269,14 +314,32 @@ for package in $packageList; do
 								rm -f "$origFile2"
 								rm -f "$fileSet2/$baseName.USE_ORIGINAL"
 							else
-								logMessage "ERROR $baseName replacement differs $version2 $version1 but origials are identical"
+								logMessage "ERROR $package: $baseName replacement differs $version2 $version1 but origials are identical"
 							fi
 						fi
 					fi
-                fi
+				# no stock files but existing file set
+				elif [ -d $fileSet2 ] ; then
+					if [ -f "$origFile2" ]; then
+						cmp -s "$origFile2" "$stockFile1"
+						if [ $? -eq 0 ] ;then
+							logMessage "$package: moving $baseName $version2 to $version1 (existing FS)"
+							mv -f "$origFile2" "$origFile1"
+							fileSetInUse=true
+							if [ -f "$replacementFile2" ]; then
+								mv -f "$replacementFile2" "$replacementFile1"
+							elif [ -f "$replacementFile2.USE_ORIGINAL" ]; then
+								mv -f "$replacementFile2.USE_ORIGINAL" "$replacementFile1.USE_ORIGINAL"
+							else
+								logMessage "ERROR $package: can't move $baseName $version2 to $version1"
+								touch "$replacementFile1.NO_REPLACEMENT"
+							fi
+						fi
+					fi
+				fi
             done # for version2
 
-			# only change file set if orig does not exist or it does NOT match the file from OriginalFiles
+			# only change file set if orig does not exist or it does NOT match the file from StockFiles
 			if [ -f "$origFile1" ]; then
 				cmp -s "$stockFile1" "$origFile1"
 				if [ $? -eq 0 ]; then
@@ -288,44 +351,35 @@ for package in $packageList; do
 				newOrig=true
 			fi
 			if $newOrig ; then
-				logMessage "$package $version1 $baseName fetching original file"
 				cp "$stockFile1" "$origFile1"
+				fileSetInUse=true
 			fi
 			# if replacement already exists, don't touch it but flag a manual check should be made
-			if [ -f "$fileSet1/$baseName" ]; then
+			if [ -f "$replacementFile1" ]; then
+				fileSetInUse=true
 				if $newOrig ; then
-					logMessage "WARNING new original found but existing replacement - CHECK REPLACEMENT"
-					touch "$fileSet1/$baseName.CHECK_REPLACEMENT"
-					rm -f "$fileSet1/$baseName.USE_ORIGINAL"
+					logMessage "WARNING $package: $baseName new original found but existing replacement - CHECK REPLACEMENT"
+					touch "$replacementFile1.CHECK_REPLACEMENT"
+					rm -f "$replacementFile1.USE_ORIGINAL"
 				fi
-			elif [ ! -e "$fileSet1/$baseName.USE_ORIGINAL" ]; then
-				logMessage "ERROR $package $version1 $baseName - no replacement file"
-				touch "$fileSet1/$baseName.NO_REPLACEMENT"
+			elif [ ! -e "$replacementFile1.USE_ORIGINAL" ]; then
+				logMessage "ERROR $package: $version1 $baseName - no replacement file"
+				touch "$replacementFile1.NO_REPLACEMENT"
+				fileSetInUse=true
 			fi
         done # for file
 
-        # remove empty file sets
-        $(ls -1qA $fileSet1 | grep  -vq "^\.")
-        if [ $? -ne 0 ]; then
-            # report removal of existing file sets, but not those just created
-            if ! $newFileSet ; then
-                logMessage "$package $version1 file set empty -- removing"
-            fi
-            rm -rf $fileSet1
-        # report creation of a new file set (created above)
-        elif $newFileSet ; then
-            logMessage "$package $version1 created new file set"
-        fi
+		if $fileSetInUse ; then
+			touch "$fileSet1/RETAIN_THIS_VERSION"
+		fi
     done  # for v1
 
     # check for file sets that no longer exist in original files
-    packageList=($(ls -d "$packageFiles"/v*))
+    packageList=($(ls -d "$packageFiles"/v* 2> /dev/null))
     for v1 in ${packageList[@]} ; do
         version=$(basename $v1)
         fileSet="$packageFiles/$version"
         if [ -d "$fileSet" ]; then
-			rm -f "$fileSet/"*MATCHES_PREVIOUS
-
             # check for real files (not sym-links)
             # if none are found, file set can be deleted
             fileSetEmpty=true
@@ -356,12 +410,23 @@ for package in $packageList; do
                
             done
             if $fileSetEmpty ; then
-                logMessage "$package $version - deleting empty file set"
+				# log removal of a previous file set
+				if [ ! -f "$fileSet/NEW_FILE_SET" ]; then
+					logMessage "$package: removing empty file set $version"
+				fi
                 rm -rf $fileSet
-            # not in originalFiles
-            elif [ ! -d "$originalFiles/$version" ]; then
-                logMessage "WARNING $package $version not in OriginalFiles - manual remove is OK"
+            # not in stockFiles
+            elif [ ! -d "$stockFiles/$version" ]; then
+                logMessage "WARNING $package: $version not in stock files - manual remove is OK"
+				touch "$fileSet/UNUSED_FILE_SET"
+			elif [ ! -f "$fileSet/RETAIN_THIS_VERSION" ]; then
+                logMessage "WARNING $package: $version is not a released version - manual remove is OK"
+				touch "$fileSet/UNUSED_FILE_SET"
             fi
+			# remove temporary flag files
+			rm -f "$fileSet/"*MATCHES_PREVIOUS
+			rm -f "$fileSet/RETAIN_THIS_VERSION"
+			rm -f "$fileSet/NEW_FILE_SET"
         fi
     done
 done
