fixed: setup scripts fail if no fileList file

diff --git a/updatePackage b/updatePackage
--- a/updatePackage
+++ b/updatePackage
@@ -88,8 +88,8 @@
 #	for this reason, preserving the working copy is recommended if errors are expected
 
 # set allPackages to all packages this script should evalueate if no options are included
-allPackages="SetupHelper GuiMods ExtTransferSwitch ShutdownMonitor VeCanSetup RpiDisplaySetup RpiGpioSetup"
-## GeneratorConnector TankRepeater are obsolete and file sets should not be updated.
+allPackages="SetupHelper GuiMods ShutdownMonitor VeCanSetup RpiDisplaySetup RpiGpioSetup"
+## ExtTransferSwitch GeneratorConnector TankRepeater are obsolete and file sets should not be updated.
 
 
 # attempt to locate SharedUtilities based on the location of this script
@@ -438,8 +438,8 @@ if [ "$globalEndAction" == "restore" ]; then
 fi
 
 # get helper resources version for later
-if [ -f "$packageRoot/SetupHelper/version" ]; then
-	shVersion=$( cat "$packageRoot/SetupHelper/version" )
+if [ -f "$packageRoot/SetupHelper/HelperResources/version" ]; then
+	shVersion=$( cat "$packageRoot/SetupHelper/HelperResources/version" )
 	versionStringToNumber $shVersion
 	shVersionNumber=$versionNumber
 else
@@ -536,8 +536,8 @@ for package in $packageList; do
 
 	# compute compatible version range - use values in original package
 	if [ -f "$sourceDirectory/obsoleteVersion" ]; then
-		tempVersion=$(cat "$sourceDirectory/obsoleteVersion")
-		if versionStringToNumber $tempVersion ; then
+		obsoleteVersio=$(cat "$sourceDirectory/obsoleteVersion")
+		if versionStringToNumber $obsoleteVersio ; then
 			obsoleteVersionNumber=$versionNumber
 		else
 			logMessage "ERROR $package obsoleteVersion $versionStringToNumberStatus - skipping package"
@@ -547,52 +547,17 @@ for package in $packageList; do
 		obsoleteVersionNumber=9999999999999999
 	fi
 	if [ -f "$sourceDirectory/firstCompatibleVersion" ]; then
-		tempVersion=$(cat "$sourceDirectory/firstCompatibleVersion")
-		if versionStringToNumber $tempVersion ; then
-			firstVersionNumber=$versionNumber
-		else
-			logMessage "ERROR $package: firstCompatibleVersion $versionStringToNumberStatus - skipping package"
-			continue	# next package
-		fi
+		firstCompatibleVersion=$(cat "$sourceDirectory/firstCompatibleVersion")
+	# limit packages to v2.71 and newer
+	else
+		firstCompatibleVersion='v2.71'
+	fi
+	if versionStringToNumber $firstCompatibleVersion ; then
 		firstVersionNumber=$versionNumber
 	else
-		firstVersionNumber=0
+		logMessage "ERROR $package: firstCompatibleVersion $versionStringToNumberStatus - skipping package"
+		continue	# next package
 	fi
-
-	# append the package's existing file sets NOT in the stock versions
-	#	to the END of the stock files list
-	#	this insures these file sets contain only files used by that or other unused versions
-	sourceFileSets=($(ls -d "$sourceFiles"/v[0-9]* 2> /dev/null))
-	tempList=()
-	for entry in ${sourceFileSets[@]} ; do
-		version=$(basename $entry)
-		if [ ! -d "$stockFiles/$version" ]; then
-			if ! versionStringToNumber $version ; then
-				logMessage "ERROR $package: file set name $versionStringToNumberStatus - skipping package"
-				continue	# next package
-			fi
-			tempList+=($version:$versionNumber)
-		fi
-	done
-	existingFileSets=( $(echo ${tempList[@]} | tr ' ' '\n' | sort -t ':' -r -n -k 2 | uniq ) )
-	allFileSets=(${stockVersionList[@]})
-	allFileSets+=(${existingFileSets[@]})
-
-	# move incompatible versions to the end of the list
-	#	so that real files end up in a supported file set
-	obsoleteFileSets=()
-	tempList=()
-	for entry in ${allFileSets[@]} ; do
-		IFS=':' read version versionNumber <<< "$entry"
-		if (( $versionNumber >= $obsoleteVersionNumber )) || (( $versionNumber < $firstVersionNumber )); then
-			obsoleteFileSets+=($version:$versionNumber)
-		else
-			tempList+=($version:$versionNumber)
-		fi
-	done
-	allFileSets=(${tempList[@]})
-	allFileSets+=(${obsoleteFileSets[@]})
-	allFileSetsLength=${#allFileSets[@]}
 
 	# make copy of source package FileSets
 	replaceCopy=false
@@ -618,6 +583,41 @@ for package in $packageList; do
 			cp -pR "$sourceDirectory/HelperResources" "$workingDirectory"
 		fi
 	fi
+
+	# append the package's existing file sets NOT in the stock versions
+	#	to the END of the stock files list
+	#	this insures these file sets contain only files used by that or other unused versions
+	sourceFileSets=($(ls -d "$workingFiles"/v[0-9]* 2> /dev/null))
+	tempList=()
+	for entry in ${sourceFileSets[@]} ; do
+		version=$(basename $entry)
+		if [ ! -d "$stockFiles/$version" ]; then
+			if ! versionStringToNumber $version ; then
+				logMessage "ERROR $package: file set name $versionStringToNumberStatus - can't continue"
+				exit
+			fi
+			tempList+=($version:$versionNumber)
+		fi
+	done
+	existingFileSets=( $(echo ${tempList[@]} | tr ' ' '\n' | sort -t ':' -r -n -k 2 | uniq ) )
+	allFileSets=(${stockVersionList[@]})
+	allFileSets+=(${existingFileSets[@]})
+
+	# move incompatible versions to the end of the list
+	#	so that real files end up in a supported file set
+	obsoleteFileSets=()
+	tempList=()
+	for entry in ${allFileSets[@]} ; do
+		IFS=':' read version versionNumber <<< "$entry"
+		if (( $versionNumber >= $obsoleteVersionNumber )) || (( $versionNumber < $firstVersionNumber )); then
+			obsoleteFileSets+=($version:$versionNumber)
+		else
+			tempList+=($version:$versionNumber)
+		fi
+	done
+	allFileSets=(${tempList[@]})
+	allFileSets+=(${obsoleteFileSets[@]})
+	allFileSetsLength=${#allFileSets[@]}
 
 	getFileLists "$workingFiles"
 
@@ -948,6 +948,7 @@ for package in $packageList; do
 			for (( i2 = $i1 + 1; i2 < $allFileSetsLength; i2++ )); do
 				IFS=':' read version2 version2number <<< "${allFileSets[$i2]}"
 				fileSet2="$workingFiles/$version2"
+				if ! [ -e "$fileSet2" ]; then continue; fi
 				replacement2="$fileSet2/$baseName"
 				# skip if replacement already exists
 				if [ -e "$replacement2" ] || [ -e "$replacement2.USE_ORIGINAL" ]; then
@@ -986,7 +987,21 @@ for package in $packageList; do
 	beginProgress "$package: final checks"
 	for (( i1 = 0; i1 < $allFileSetsLength; i1++ )); do
 		IFS=':' read version1 version1number <<< "${allFileSets[$i1]}"
+
+		if (( $version1number >= $obsoleteVersionNumber )) || (( $version1number < $firstVersionNumber )); then
+			incompatibleVersion=true
+		else
+			incompatibleVersion=false
+		fi
+
 		fileSet1="$workingFiles/$version1"
+		# file set should exist so this shouldn't happen but report and skip checks anyway
+		if ! [ -d "$fileSet1" ]; then
+			if ! $incompatibleVersion && ! [ -z $fileList ]; then
+				logMessage "ERROR: $package $version1 missing file set - skipping"
+			fi
+			continue
+		fi
 		outputProgressTick "."
 
 		replacementFilesExist=false
@@ -1189,7 +1204,7 @@ for package in $packageList; do
 	elif (( helperVersionNumber == pkgHelperVersionNumber )); then
 		for file in $( ls "$packageRoot/HelperResources" ); do
 			baseName=$( basename $file )
-			if [[ "$packageRoot/HelperResources/$baseName" -nt "$workingDirectory/HelperResources$( baseName $file )" ]]; then
+			if [[ "$packageRoot/HelperResources/$baseName" -nt "$workingDirectory/HelperResources/$baseName" ]]; then
 				updateHelperResources=true
 				break
 			fi
