updateFileSets: fixed: stale symlinks not removed; updateFileSets: addd progress

diff --git a/updateFileSets b/updateFileSets
--- a/updateFileSets
+++ b/updateFileSets
@@ -58,26 +58,32 @@ stockFiles="$packageRoot/StockVenusOsFiles"
 ((totalErrors=0))
 ((totalWarnings=0))
 
-outputtingDots=false
+outputtingProgress=false
 
-logMessage ()
+function logMessage ()
 {
-	if $outputtingDots ; then
-		echo
-		outputtingDots=false
+	if $outputtingProgress ; then
+		clearProgress
 	fi
     echo "$*"
     if [[ "$*" == *"ERROR"* ]]; then
         ((totalErrors++))
+        ((packageErrors++))
     elif [[ "$*" == *"WARNING"* ]]; then
         ((totalWarnings++))
     fi
 }
 
-outputProgress ()
+function outputProgress ()
 {
-	echo -n "$1"
-	outputtingDots=true
+	echo -en "$1"
+	outputtingProgress=true
+}
+
+function clearProgress ()
+{
+	echo -ne "\r\033[2K"
+	outputtingProgress=false
 }
 
 function versionStringToNumber ()
@@ -164,7 +170,7 @@ for package in $packageList; do
         logMessage "ERROR $package: empty file list"
         continue
     fi
-	logMessage "$package: checking file sets"
+	##################logMessage "$package: updating file sets"
 
 	# add a package's existing file sets to stock versions
 	existingFileSets=($(ls -d "$packageFiles"/v* 2> /dev/null))
@@ -183,6 +189,7 @@ for package in $packageList; do
 		rm -f "$fileSet/NEW_FILE_SET"
 		rm -f "$fileSet/INCOMPLETE"
 		rm -f "$fileSet/COMPLETE"
+		rm -f "$fileSet/LINKS_ONLY"
 		rm -f "$fileSet/"*.NO_ORIG
 		rm -f "$fileSet/"*.NO_REPLACEMENT
 		rm -f "$fileSet/"*.NO_REPLACEMENT_LINK
@@ -191,6 +198,7 @@ for package in $packageList; do
 
 	# process versions in stock files
     for entry1 in ${versionList[@]} ; do
+		packageErrors=0
 		IFS=':' read version1 version1number <<< "$entry1"
         fileSet1="$packageFiles/$version1"
 
@@ -215,6 +223,8 @@ for package in $packageList; do
 			fi
 			continue
 		fi
+		clearProgress
+		outputProgress "$package $version1 "
 
         if [ ! -d "$fileSet1" ]; then
             mkdir "$fileSet1"
@@ -235,6 +245,7 @@ for package in $packageList; do
 			if [ -f "$origFile1.MATCHES_PREVIOUS" ]; then
 				continue
 			fi
+			outputProgress "."
 
             # use alternate original if present
             if [ -f "$packageFiles/$baseName.ALT_ORIG" ]; then
@@ -343,6 +354,7 @@ for package in $packageList; do
 						if [ -L "$replacementFile2" ]; then
 							rm -f "$replacementFile2"
 						fi
+						logMessage "ERROR $package: no replacement link for $baseName $version2"
 						touch "$replacementFile2.NO_REPLACEMENT_LINK"
 						touch "$fileSet2/INCOMPLETE"
 					fi
@@ -386,75 +398,80 @@ for package in $packageList; do
 	# COMPLETE tells _checkFileSets to skip all checks and accept the file set as is
 	if [ -f "$fileSet1/INCOMPLETE" ]; then
 		rm -f "$fileSet1/COMPLETE"
-		outputProgress "X"
+		packageHasErrors=true
 	else
 		touch "$fileSet1/COMPLETE"
-		outputProgress "."
 	fi
 
-    done  # for v1
+    done  # for entry1
 
-    # check for file sets that no longer exist in stock files
+    # cleanup file sets
     versionList1=($(ls -d "$packageFiles"/v* 2> /dev/null))
-    for v1 in ${versionList1[@]} ; do
-        version=$(basename $v1)
+    for fileSet in ${versionList1[@]} ; do
+        version=$(basename $fileSet)
+		clearProgress
+		outputProgress "$package $version cleanup"
         fileSet="$packageFiles/$version"
         if [ ! -d "$fileSet" ]; then
 			continue
 		fi
 		# check for existing files
 		# if none are found, file set can be deleted
-		fileSetEmpty=true
+		replacementFilesExist=false
+		replacmentSymLinksExist=false
+		for file in $fileList ; do
+			baseName=$(basename "$file")
+			replacementFile="$fileSet/$baseName"
+			if [ -L "$replacementFile" ]; then
+				replacmentSymLinksExist=true
+			elif [ -f "$replacementFile" ]; then
+				replacementFilesExist=true
+			elif [ -f "$replacementFile.NO_REPLACEMENT" ]; then
+				replacementFilesExist=true
+			elif [ -f "$replacementFile.NO_REPLACEMENT_LINK" ]; then
+				replacementFilesExist=true
+			elif [ -f "$replacementFile.CHECK_REPLACEMENT" ]; then
+				replacementFilesExist=true
+			elif [ -f "$replacementFile.USE_ORIGINAL" ]; then
+				replacementFilesExist=true
+			fi
+			if [ -f "$replacement.orig" ]; then
+				replacementFilesExist=true
+			fi
+		done
 
-		# keep file set if this version is in stock files
+		# file set is in stock files
 		if [ -d "$stockFiles/$version" ]; then
-			fileSetEmpty=false
+			if ! $replacementFilesExist && $replacmentSymLinksExist ; then
+				touch "$fileSet/LINKS_ONLY"
+			fi
+		# not in stock files list
 		else
 			logMessage "$package $version not in stock files"
-			for file in $fileList ; do
-				baseName=$(basename "$file")
-				replacementFile="$fileSet/$baseName"
-				if [ -f "$replacementFile" ] && [ ! -L "$replacementFile" ]; then
-					fileSetEmpty=false
-					break;
-				fi
-				if [ -f "$replacement.orig" ]; then
-					fileSetEmpty=false
-					break;
-				fi
-				if [ -f "$replacementFile.NO_REPLACEMENT" ]; then
-					 fileSetEmpty=false
-					break;
-				fi
-				if [ -f "$replacementFile.NO_REPLACEMENT_LINK" ]; then
-					 fileSetEmpty=false
-					break;
-				fi
-				if [ -f "$replacementFile.CHECK_REPLACEMENT" ]; then
-					 fileSetEmpty=false
-					break;
-				fi
-				if [ -f "$replacementFile.USE_ORIGINAL" ]; then
-					 fileSetEmpty=false
-					break;
-				fi
-			done
-			if $fileSetEmpty ; then
-				# log removal of a previous file set
+			if $replacementFilesExist ; then
+				logMessage "WARNING $package: $version no longer used but not empty - manual remove is OK"
+				touch "$fileSet/UNUSED_FILE_SET"
+			# no files (empty file set)
+			else
+				# log removal of a previous file set if not created with this run
+				# if it was created with this run, delete it silently
 				if [ ! -f "$fileSet/NEW_FILE_SET" ]; then
 					logMessage "$package: removing empty file set $version"
 				fi
 				rm -rf $fileSet
-			else
-				logMessage "WARNING $package: $version no longer used but not empty - manual remove is OK"
-				touch "$fileSet/UNUSED_FILE_SET"
 			fi
 		fi
 
 		# remove temporary flag files
 		rm -f "$fileSet/"*MATCHES_PREVIOUS
 		rm -f "$fileSet/NEW_FILE_SET"
-    done # for v1
+    done # for fileSet (cleanup)
+	if (( $packageErrors > 0 )) ; then
+		logMessage "$package: $packageErrors ERRORS"
+	else
+		logMessage "$package: no errors"
+		echo "foo" >/dev/null
+	fi
 done # for package
 
 if [ "$totalErrors" == 0 ]; then
